server:
  port: 8008

spring:
  application:
    name: steet

  datasource:
    url: jdbc:postgresql://localhost:5432/steet
    username: postgres
    password: pstgr-sandev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

  # security:
  #   user:
  #     name: admin
  #     password: admin
